/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalsprojecttest;

import java.awt.CardLayout;

/**
 *
 * @author lawre
 */
public class app_ui extends javax.swing.JFrame {

    /**
     * Creates new form app_ui
     */
    public app_ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Main_Menu = new javax.swing.JPanel();
        mainLabel1 = new javax.swing.JLabel();
        smallScaleBtn = new javax.swing.JButton();
        wedBtn = new javax.swing.JButton();
        CorpoBtn = new javax.swing.JButton();
        EventInfo = new javax.swing.JPanel();
        NoAttendLabel = new javax.swing.JLabel();
        EvDateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        noAttendField = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        ok_eventInfoBtn = new javax.swing.JButton();
        cancel_eventInfoBtn = new javax.swing.JButton();
        Menu_Picker = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        western_label = new javax.swing.JLabel();
        westScrollPane = new javax.swing.JScrollPane();
        westernTxtArea = new javax.swing.JTextArea();
        WestSelectBtn = new javax.swing.JButton();
        phPanel = new javax.swing.JPanel();
        phScrollPane = new javax.swing.JScrollPane();
        phTxtArea = new javax.swing.JTextArea();
        Filipino_label = new javax.swing.JLabel();
        PhSelectBtn1 = new javax.swing.JButton();
        medPanel = new javax.swing.JPanel();
        medScrollPane1 = new javax.swing.JScrollPane();
        medTxtArea1 = new javax.swing.JTextArea();
        Med_Label = new javax.swing.JLabel();
        PhSelectBtn2 = new javax.swing.JButton();
        Payment = new javax.swing.JPanel();
        paymentLabel = new javax.swing.JLabel();
        invoiceLabel = new javax.swing.JLabel();
        paxLabel = new javax.swing.JLabel();
        perHeadLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        ppHeadTextField = new javax.swing.JTextField();
        paxTextField1 = new javax.swing.JTextField();
        subtotalTextField1 = new javax.swing.JTextField();
        payOptionPanel = new javax.swing.JPanel();
        payOptionsPanel = new javax.swing.JPanel();
        payOptionField = new javax.swing.JLabel();
        cashSelect = new javax.swing.JButton();
        creditSelect = new javax.swing.JButton();
        creditPanel = new javax.swing.JPanel();
        ccInfoLabel = new javax.swing.JLabel();
        ccNumberLabel = new javax.swing.JLabel();
        ccNameLabel = new javax.swing.JLabel();
        ccOkButton = new javax.swing.JButton();
        cashPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AA Catering App");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        Main_Menu.setBackground(new java.awt.Color(255, 255, 255));

        mainLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mainLabel1.setText("Welcome to AA Catering!");

        smallScaleBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        smallScaleBtn.setText("Small-Scale");
        smallScaleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smallScaleBtnMouseClicked(evt);
            }
        });

        wedBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        wedBtn.setText("Weddings/Occasions");

        CorpoBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CorpoBtn.setText("Corporate Events");

        javax.swing.GroupLayout Main_MenuLayout = new javax.swing.GroupLayout(Main_Menu);
        Main_Menu.setLayout(Main_MenuLayout);
        Main_MenuLayout.setHorizontalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_MenuLayout.createSequentialGroup()
                .addGroup(Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_MenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_MenuLayout.createSequentialGroup()
                        .addContainerGap(420, Short.MAX_VALUE)
                        .addGroup(Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(smallScaleBtn)
                            .addComponent(wedBtn)
                            .addComponent(CorpoBtn))
                        .addGap(38, 38, 38)))
                .addGap(172, 172, 172))
        );

        Main_MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CorpoBtn, smallScaleBtn, wedBtn});

        Main_MenuLayout.setVerticalGroup(
            Main_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel1)
                .addGap(106, 106, 106)
                .addComponent(smallScaleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wedBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorpoBtn)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jPanel2.add(Main_Menu, "main_menu");

        EventInfo.setBackground(new java.awt.Color(255, 255, 255));

        NoAttendLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NoAttendLabel.setText("Number of attendees:");

        EvDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EvDateLabel.setText("Date of Event: ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Enter event info below");

        noAttendField.setColumns(25);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField1.setText("dd/MM/yyyy");

        ok_eventInfoBtn.setText("Okay");
        ok_eventInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_eventInfoBtnMouseClicked(evt);
            }
        });

        cancel_eventInfoBtn.setText("Cancel");
        cancel_eventInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_eventInfoBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EventInfoLayout = new javax.swing.GroupLayout(EventInfo);
        EventInfo.setLayout(EventInfoLayout);
        EventInfoLayout.setHorizontalGroup(
            EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventInfoLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(EventInfoLayout.createSequentialGroup()
                        .addGroup(EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ok_eventInfoBtn)
                            .addGroup(EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NoAttendLabel)
                                .addComponent(EvDateLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noAttendField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel_eventInfoBtn))))
                .addGap(236, 236, 236))
        );

        EventInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EvDateLabel, NoAttendLabel});

        EventInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFormattedTextField1, noAttendField});

        EventInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancel_eventInfoBtn, ok_eventInfoBtn});

        EventInfoLayout.setVerticalGroup(
            EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventInfoLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoAttendLabel)
                    .addComponent(noAttendField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EvDateLabel)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EventInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_eventInfoBtn)
                    .addComponent(cancel_eventInfoBtn))
                .addContainerGap(252, Short.MAX_VALUE))
        );

        jPanel2.add(EventInfo, "EventPanel");

        Menu_Picker.setBackground(new java.awt.Color(255, 255, 255));
        Menu_Picker.setLayout(new java.awt.GridLayout());

        western_label.setText("Western Menu");

        westernTxtArea.setEditable(false);
        westernTxtArea.setColumns(20);
        westernTxtArea.setRows(5);
        westernTxtArea.setText("Menu Set:\n\n\nSteak\n\nBeer Battered Fish\n\nButtered Vegetables\n\nPasta Bolognese or Carbonara\n\nHouse Iced Tea \n\nPHP 150/ pax");
        westScrollPane.setViewportView(westernTxtArea);

        WestSelectBtn.setText("Select");
        WestSelectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WestSelectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(western_label)
                    .addComponent(westScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WestSelectBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(western_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(westScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WestSelectBtn)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        Menu_Picker.add(westPanel);

        phTxtArea.setEditable(false);
        phTxtArea.setColumns(20);
        phTxtArea.setRows(5);
        phTxtArea.setText("Menu Set:\n\n\nSteak\n\nBeer Battered Fish\n\nButtered Vegetables\n\nPasta Bolognese or Carbonara\n\nHouse Iced Tea \n\nPHP 150/ pax");
        phScrollPane.setViewportView(phTxtArea);

        Filipino_label.setText("Filipino Menu");

        PhSelectBtn1.setText("Select");

        javax.swing.GroupLayout phPanelLayout = new javax.swing.GroupLayout(phPanel);
        phPanel.setLayout(phPanelLayout);
        phPanelLayout.setHorizontalGroup(
            phPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(phPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Filipino_label)
                    .addComponent(phScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhSelectBtn1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        phPanelLayout.setVerticalGroup(
            phPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Filipino_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhSelectBtn1)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        Menu_Picker.add(phPanel);

        medTxtArea1.setEditable(false);
        medTxtArea1.setColumns(20);
        medTxtArea1.setRows(5);
        medTxtArea1.setText("Menu Set:\n\n\nLamb Chops\n\nArrosticini\n\nGreek Salad\n\nPaella or Tagliatalle\n\nHouse Iced Tea \n\nPHP 200/ pax");
        medScrollPane1.setViewportView(medTxtArea1);

        Med_Label.setText("Mediterranean Menu");

        PhSelectBtn2.setText("Select");

        javax.swing.GroupLayout medPanelLayout = new javax.swing.GroupLayout(medPanel);
        medPanel.setLayout(medPanelLayout);
        medPanelLayout.setHorizontalGroup(
            medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Med_Label)
                    .addComponent(medScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhSelectBtn2))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        medPanelLayout.setVerticalGroup(
            medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Med_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhSelectBtn2)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        Menu_Picker.add(medPanel);

        jPanel2.add(Menu_Picker, "menuPanel");

        paymentLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        paymentLabel.setText("Payment");

        invoiceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        invoiceLabel.setText("Invoice");

        paxLabel.setText("Pax");

        perHeadLabel.setText("price per head");

        subtotalLabel.setText("subtotal");

        ppHeadTextField.setEditable(false);
        ppHeadTextField.setColumns(15);
        ppHeadTextField.setText(" ");
        ppHeadTextField.setToolTipText("");

        paxTextField1.setEditable(false);
        paxTextField1.setColumns(15);
        paxTextField1.setText(" ");
        paxTextField1.setToolTipText("");

        subtotalTextField1.setEditable(false);
        subtotalTextField1.setColumns(15);
        subtotalTextField1.setText(" ");
        subtotalTextField1.setToolTipText("");

        payOptionPanel.setBackground(new java.awt.Color(255, 255, 255));
        payOptionPanel.setLayout(new java.awt.CardLayout());

        payOptionField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        payOptionField.setText("Select a payment option:");

        cashSelect.setText("Cash");

        creditSelect.setText("Credit");
        creditSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout payOptionsPanelLayout = new javax.swing.GroupLayout(payOptionsPanel);
        payOptionsPanel.setLayout(payOptionsPanelLayout);
        payOptionsPanelLayout.setHorizontalGroup(
            payOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(payOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cashSelect)
                        .addComponent(creditSelect))
                    .addComponent(payOptionField))
                .addContainerGap(400, Short.MAX_VALUE))
        );

        payOptionsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cashSelect, creditSelect});

        payOptionsPanelLayout.setVerticalGroup(
            payOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payOptionField)
                .addGap(27, 27, 27)
                .addComponent(cashSelect)
                .addGap(18, 18, 18)
                .addComponent(creditSelect)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        payOptionPanel.add(payOptionsPanel, "payOptionPanel");

        ccInfoLabel.setText("Enter your credit card info here");

        ccNumberLabel.setText("Card Number: ");

        ccNameLabel.setText("Customer Name:");

        ccOkButton.setText("OK");

        javax.swing.GroupLayout creditPanelLayout = new javax.swing.GroupLayout(creditPanel);
        creditPanel.setLayout(creditPanelLayout);
        creditPanelLayout.setHorizontalGroup(
            creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ccInfoLabel)
                    .addComponent(ccNumberLabel)
                    .addComponent(ccNameLabel)
                    .addComponent(ccOkButton))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        creditPanelLayout.setVerticalGroup(
            creditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ccInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ccNameLabel)
                .addGap(36, 36, 36)
                .addComponent(ccOkButton)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        payOptionPanel.add(creditPanel, "creditPanel");

        javax.swing.GroupLayout cashPanelLayout = new javax.swing.GroupLayout(cashPanel);
        cashPanel.setLayout(cashPanelLayout);
        cashPanelLayout.setHorizontalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        cashPanelLayout.setVerticalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        payOptionPanel.add(cashPanel, "cashPanel");

        javax.swing.GroupLayout PaymentLayout = new javax.swing.GroupLayout(Payment);
        Payment.setLayout(PaymentLayout);
        PaymentLayout.setHorizontalGroup(
            PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentLayout.createSequentialGroup()
                .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paxLabel)
                            .addComponent(perHeadLabel)
                            .addComponent(subtotalLabel))
                        .addGap(18, 18, 18)
                        .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(paxTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ppHeadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotalTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(invoiceLabel))
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(paymentLabel)))
                .addGap(97, 97, 97)
                .addComponent(payOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PaymentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {paxLabel, perHeadLabel, subtotalLabel});

        PaymentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {paxTextField1, ppHeadTextField, subtotalTextField1});

        PaymentLayout.setVerticalGroup(
            PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paymentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoiceLabel)
                .addGap(18, 18, 18)
                .addGroup(PaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addComponent(paxTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ppHeadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(subtotalTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaymentLayout.createSequentialGroup()
                        .addComponent(paxLabel)
                        .addGap(21, 21, 21)
                        .addComponent(perHeadLabel)
                        .addGap(27, 27, 27)
                        .addComponent(subtotalLabel)))
                .addContainerGap(264, Short.MAX_VALUE))
            .addComponent(payOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(Payment, "payPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smallScaleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smallScaleBtnMouseClicked
        CardLayout card = (CardLayout)jPanel2.getLayout();
        card.show(jPanel2, "EventPanel");
    }//GEN-LAST:event_smallScaleBtnMouseClicked

    private void cancel_eventInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_eventInfoBtnMouseClicked
        CardLayout card = (CardLayout)jPanel2.getLayout();
        card.show(jPanel2, "main_menu");
    }//GEN-LAST:event_cancel_eventInfoBtnMouseClicked

    private void ok_eventInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_eventInfoBtnMouseClicked
        CardLayout card = (CardLayout)jPanel2.getLayout();
        card.show(jPanel2, "menuPanel");
    }//GEN-LAST:event_ok_eventInfoBtnMouseClicked

    private void WestSelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WestSelectBtnActionPerformed
        CardLayout card = (CardLayout)jPanel2.getLayout();
        card.show(jPanel2, "payPanel");
    }//GEN-LAST:event_WestSelectBtnActionPerformed

    private void creditSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditSelectActionPerformed
        CardLayout card = (CardLayout)payOptionPanel.getLayout();
        card.show(payOptionPanel, "creditPanel");
    }//GEN-LAST:event_creditSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app_ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CorpoBtn;
    private javax.swing.JLabel EvDateLabel;
    private javax.swing.JPanel EventInfo;
    private javax.swing.JLabel Filipino_label;
    private javax.swing.JPanel Main_Menu;
    private javax.swing.JLabel Med_Label;
    private javax.swing.JPanel Menu_Picker;
    private javax.swing.JLabel NoAttendLabel;
    private javax.swing.JPanel Payment;
    private javax.swing.JButton PhSelectBtn1;
    private javax.swing.JButton PhSelectBtn2;
    private javax.swing.JButton WestSelectBtn;
    private javax.swing.JButton cancel_eventInfoBtn;
    private javax.swing.JPanel cashPanel;
    private javax.swing.JButton cashSelect;
    private javax.swing.JLabel ccInfoLabel;
    private javax.swing.JLabel ccNameLabel;
    private javax.swing.JLabel ccNumberLabel;
    private javax.swing.JButton ccOkButton;
    private javax.swing.JPanel creditPanel;
    private javax.swing.JButton creditSelect;
    private javax.swing.JLabel invoiceLabel;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mainLabel1;
    private javax.swing.JPanel medPanel;
    private javax.swing.JScrollPane medScrollPane1;
    private javax.swing.JTextArea medTxtArea1;
    private javax.swing.JTextField noAttendField;
    private javax.swing.JButton ok_eventInfoBtn;
    private javax.swing.JLabel paxLabel;
    private javax.swing.JTextField paxTextField1;
    private javax.swing.JLabel payOptionField;
    private javax.swing.JPanel payOptionPanel;
    private javax.swing.JPanel payOptionsPanel;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JLabel perHeadLabel;
    private javax.swing.JPanel phPanel;
    private javax.swing.JScrollPane phScrollPane;
    private javax.swing.JTextArea phTxtArea;
    private javax.swing.JTextField ppHeadTextField;
    private javax.swing.JButton smallScaleBtn;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JTextField subtotalTextField1;
    private javax.swing.JButton wedBtn;
    private javax.swing.JPanel westPanel;
    private javax.swing.JScrollPane westScrollPane;
    private javax.swing.JTextArea westernTxtArea;
    private javax.swing.JLabel western_label;
    // End of variables declaration//GEN-END:variables
}
